-- CreateEnum
CREATE TYPE "OutboxStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "hourlyRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "baseSalary" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Ingredient" ALTER COLUMN "costPerUnit" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Promotion" ALTER COLUMN "discountValue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "minPurchase" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "totalAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "netAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalCogs" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "price" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "PurchaseOrderItem" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "ShiftSettlement" ALTER COLUMN "expectedCash" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "actualCash" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "expectedCreditCard" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "actualCreditCard" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "expectedQR" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "actualQR" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "difference" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Payslip" ALTER COLUMN "basePay" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "otPay" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "bonuses" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "grossPay" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "taxDeduction" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "socialSecurity" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "otherDeductions" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "netPay" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "MaintenanceLog" ALTER COLUMN "cost" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "JournalEntryLine" ALTER COLUMN "debit" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "credit" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "ProductionOrder" ALTER COLUMN "actualCost" SET DATA TYPE DECIMAL(19,4);

-- CreateTable
CREATE TABLE "OutboxEvent" (
    "id" SERIAL NOT NULL,
    "eventType" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "OutboxStatus" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "lastError" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "OutboxEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "OutboxEvent_status_createdAt_idx" ON "OutboxEvent"("status", "createdAt");
