// API response / domain types — decoupled from Prisma database models.

export type Role = 'SUPER_ADMIN' | 'MANAGER' | 'STAFF';
export type EmploymentType = 'FULL_TIME' | 'PART_TIME';
export type OrderStatus = 'PENDING' | 'PREPARING' | 'COMPLETED' | 'CANCELLED';
export type PaymentMethod = 'CASH' | 'CREDIT_CARD' | 'QR_PROMPTPAY';
export type POStatus = 'DRAFT' | 'PENDING' | 'APPROVED' | 'RECEIVED';
export type TransferStatus = 'PENDING' | 'SHIPPED' | 'COMPLETED' | 'CANCELLED';
export type ShiftStatus = 'SCHEDULED' | 'COMPLETED' | 'ABSENT' | 'CANCELLED';
export type LeaveType = 'SICK' | 'ANNUAL' | 'UNPAID';
export type LeaveStatus = 'PENDING' | 'APPROVED' | 'REJECTED';
export type PayrollStatus = 'DRAFT' | 'APPROVED' | 'PAID';
export type SettlementStatus = 'PENDING' | 'APPROVED' | 'REJECTED';
export type DiscountType = 'PERCENTAGE' | 'FIXED_AMOUNT';
export type Tier = 'REGULAR' | 'SILVER' | 'GOLD' | 'PLATINUM';
export type AccountType = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
export type EquipmentType = 'ESPRESSO_MACHINE' | 'GRINDER' | 'BLENDER' | 'POS_SYSTEM' | 'REFRIGERATOR' | 'OTHER';
export type EquipmentStatus = 'ACTIVE' | 'MAINTENANCE' | 'BROKEN' | 'RETIRED';
export type ProductionStatus = 'DRAFT' | 'PLANNED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
export type BatchStatus = 'ACTIVE' | 'DEPLETED' | 'EXPIRED';

export interface Branch {
  id: number;
  name: string;
  location?: string | null;
  isCentralKitchen?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface User {
  id: number;
  email: string;
  name: string | null;
  role: Role;
  employmentType?: EmploymentType;
  branchId: number | null;
  hourlyRate?: number;
  baseSalary?: number;
  createdAt?: string;
  updatedAt?: string;
  branch?: Branch | null;
}

export interface Product {
  id: number;
  name: string;
  price: number;
  category: string;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
  recipeItems?: RecipeItem[];
}

export interface RecipeItem {
  id: number;
  productId: number;
  ingredientId: number;
  quantity: number;
  ingredient?: Ingredient;
}

export interface Ingredient {
  id: number;
  name: string;
  unit: string;
  costPerUnit?: number;
  primarySupplierId?: number | null;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
  primarySupplier?: Supplier | null;
}

export interface Customer {
  id: number;
  phone: string;
  name: string;
  points: number;
  tier: Tier;
  createdAt?: string;
  updatedAt?: string;
  orders?: Order[];
}

export interface Promotion {
  id: number;
  code: string;
  description: string;
  discountType: DiscountType;
  discountValue: number;
  minPurchase?: number | null;
  isActive: boolean;
  startDate?: string | null;
  endDate?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface OrderItem {
  id: number;
  orderId: number;
  productId: number;
  quantity: number;
  price: number;
  notes?: string | null;
  product?: Product;
}

export interface Order {
  id: number;
  totalAmount: number;
  discountAmount: number;
  netAmount: number;
  taxAmount: number;
  totalCogs: number;
  pointsEarned: number;
  pointsRedeemed: number;
  status: OrderStatus;
  paymentMethod: PaymentMethod;
  isTaxInvoiceRequested?: boolean;
  taxInvoiceName?: string | null;
  taxInvoiceTaxId?: string | null;
  taxInvoiceAddress?: string | null;
  userId: number;
  branchId: number;
  customerId?: number | null;
  promotionId?: number | null;
  createdAt: string;
  items?: OrderItem[];
  customer?: Customer | null;
  promotion?: Promotion | null;
  branch?: Branch;
  user?: User;
}

export interface Supplier {
  id: number;
  name: string;
  contactEmail?: string | null;
  phone?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface PurchaseOrderItem {
  id: number;
  poId: number;
  ingredientId: number;
  quantityRequested: number;
  unitPrice: number;
  ingredient?: Ingredient;
}

export interface PurchaseOrder {
  id: number;
  poNumber: string;
  branchId: number;
  supplierId: number;
  status: POStatus;
  isAutoGenerated?: boolean;
  createdAt: string;
  updatedAt?: string;
  supplier?: Supplier;
  branch?: Branch;
  items?: PurchaseOrderItem[];
}

export interface StockTransfer {
  id: number;
  fromBranchId: number;
  toBranchId: number;
  ingredientId: number;
  quantity: number;
  status: TransferStatus;
  requestedById: number;
  approvedById?: number | null;
  createdAt: string;
  updatedAt?: string;
  fromBranch?: Branch;
  toBranch?: Branch;
  ingredient?: Ingredient;
  requestedBy?: User;
}

export interface InventoryBatch {
  id: number;
  branchId: number;
  ingredientId: number;
  quantity: number;
  expiryDate?: string | null;
  poId?: number | null;
  status: BatchStatus;
  createdAt?: string;
  updatedAt?: string;
  ingredient?: Ingredient;
}

export interface BranchInventory {
  id: number;
  branchId: number;
  ingredientId: number;
  stock: number;
  minStock: number;
  updatedAt?: string;
  ingredient?: Ingredient;
}

export interface Shift {
  id: number;
  userId: number;
  branchId: number;
  startTime: string;
  endTime: string;
  status: ShiftStatus;
  createdAt?: string;
  updatedAt?: string;
  user?: User;
  branch?: Branch;
}

export interface LeaveRequest {
  id: number;
  userId: number;
  type: LeaveType;
  startDate: string;
  endDate: string;
  reason?: string | null;
  status: LeaveStatus;
  createdAt?: string;
  updatedAt?: string;
  user?: User;
}

export interface PayrollRun {
  id: number;
  month: number;
  year: number;
  status: PayrollStatus;
  branchId?: number | null;
  createdAt?: string;
  updatedAt?: string;
  payslips?: Payslip[];
  branch?: Branch | null;
}

export interface Payslip {
  id: number;
  payrollRunId: number;
  userId: number;
  standardHours: number;
  otHours: number;
  basePay: number;
  otPay: number;
  bonuses: number;
  grossPay: number;
  taxDeduction: number;
  socialSecurity: number;
  otherDeductions: number;
  netPay: number;
  createdAt?: string;
  updatedAt?: string;
  user?: User;
}

export interface Account {
  id: number;
  code: string;
  name: string;
  type: AccountType;
  description?: string | null;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface Equipment {
  id: number;
  branchId: number;
  name: string;
  type: EquipmentType;
  serialNumber?: string | null;
  status: EquipmentStatus;
  purchaseDate?: string | null;
  warrantyExpiry?: string | null;
  nextMaintenanceDate?: string | null;
  createdAt?: string;
  updatedAt?: string;
  branch?: Branch;
}

export interface ProductionOrder {
  id: number;
  orderNumber: string;
  branchId: number;
  targetIngredientId: number;
  quantityToProduce: number;
  status: ProductionStatus;
  actualCost?: number;
  plannedStartDate?: string | null;
  completedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
  branch?: Branch;
  targetIngredient?: Ingredient;
}

export interface AuditLog {
  id: number;
  userId: number;
  action: string;
  targetType: string;
  targetId?: number | null;
  details?: string | null;
  createdAt: string;
  user?: User;
}

export interface WasteLog {
  id: number;
  branchId: number;
  ingredientId: number;
  ingredient?: Ingredient;
  quantity: number;
  reason: string;
  recordedById: number;
  recordedBy?: { name: string };
  createdAt: string;
}

export interface Settlement {
  id: number;
  branchId: number;
  branch?: { name: string };
  date: string;
  expectedCash: number;
  actualCash: number;
  expectedCreditCard?: number;
  actualCreditCard?: number;
  expectedQR?: number;
  actualQR?: number;
  difference: number;
  status: SettlementStatus;
  submittedById: number;
  createdAt: string;
  updatedAt?: string;
}

export interface Expense {
  id: number;
  branchId: number;
  amount: number;
  category: string;
  description?: string;
  recordedById: number;
  recordedBy?: { name: string };
  createdAt: string;
}

export interface SettlementExpected {
  expectedCash: number;
  expectedCreditCard: number;
  expectedQR: number;
  sales: number;
  expenses: number;
}
