/** Canonical labels for URL segments used in breadcrumbs. */
export const PATH_LABELS: Record<string, string> = {
  inventory: "Inventory",
  stock: "Batches & Expiry",
  batches: "Batches & Expiry",
  "stock-in": "Receive Stock (GRN)",
  transfers: "Stock Transfers",
  waste: "Waste Logs",
  procurement: "Procurement",
  suppliers: "Suppliers",
  orders: "Purchase Orders",
  products: "Products",
  ingredients: "Raw Ingredients",
  modifiers: "Modifiers",
  costing: "Food Cost",
  kitchen: "Central Kitchen",
  boms: "Production BOM",
  hr: "Human Resources",
  employees: "Employee Directory",
  shifts: "Shift Management",
  attendance: "Attendance",
  leave: "Leave Requests",
  payroll: "Payroll",
  crm: "CRM",
  customers: "Customers & Loyalty",
  promotions: "Campaigns",
  finance: "Finance",
  overview: "Overview",
  ledger: "General Ledger",
  accounts: "Chart of Accounts",
  assets: "Assets",
  equipment: "Equipment",
  pos: "Point of Sale",
  terminal: "Terminal",
  settlement: "Settlement",
  settings: "Settings",
  audit: "Audit Trail",
  organization: "Organization",
  branches: "Branches",
  users: "Users & Roles",
  kds: "Kitchen Display",
};
