"use client";

import { useState } from "react";
import { usePurchaseOrders, useSuppliers, useIngredients, useCreatePurchaseOrder, useApprovePurchaseOrder, useRejectPurchaseOrder, useReceivePurchaseOrder } from "@/hooks/useQueries";
import { useAuth } from "@/context/AuthContext";
import { Table, Tag, Button as AntButton, Form, Select, InputNumber, Space, Steps, Popconfirm } from "antd";
import { FormModal } from "@/components/shared/form-modal";
import { Plus, CheckCircle2, XCircle, CheckSquare, Trash2, Truck } from "lucide-react";
import { toast } from "sonner";
import { AnimatedPage } from "@/components/animated-page";
import { PageHeader } from "@/components/shared/page-header";
import { DataTable } from "@/components/shared/data-table";
import { format } from "date-fns";

export default function ProcurementPage() {
  const { user, activeBranchId } = useAuth();
  const { data: posData, isLoading: loadingPos } = usePurchaseOrders();
  const { data: suppliersData, isLoading: loadingSup } = useSuppliers();
  const { data: ingredientsData, isLoading: loadingIng } = useIngredients();

  const suppliers = suppliersData || [];
  const ingredients = ingredientsData || [];
  
  let pos = posData || [];
  if (user?.role !== 'SUPER_ADMIN' || activeBranchId) {
    if (activeBranchId) {
      pos = pos.filter((po: any) => po.branchId === activeBranchId);
    }
  }

  const loading = loadingPos || loadingSup || loadingIng;

  const approveMutation = useApprovePurchaseOrder();
  const rejectMutation = useRejectPurchaseOrder();
  const receiveMutation = useReceivePurchaseOrder();
  const createMutation = useCreatePurchaseOrder();

  // Modal state
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [form] = Form.useForm();

  // Removed manual loadData with useEffect

  const handleApprove = async (poId: number) => {
    try {
      await approveMutation.mutateAsync(poId);
      toast.success("Purchase Order approved successfully!");
    } catch (error: unknown) {
      if (error instanceof Error) toast.error(error.message || "Failed to approve PO");
    }
  };

  const handleReject = async (poId: number) => {
    try {
      await rejectMutation.mutateAsync(poId);
      toast.success("Purchase Order rejected.");
    } catch (error: unknown) {
      if (error instanceof Error) toast.error(error.message || "Failed to reject PO");
    }
  };

  const handleReceive = async (poId: number) => {
    try {
      await receiveMutation.mutateAsync(poId);
      toast.success("Purchase Order received! Inventory updated.");
    } catch (error: unknown) {
      if (error instanceof Error) toast.error(error.message || "Failed to receive PO");
    }
  };

  const handleCreateSubmit = async (values: any) => {
    if (!activeBranchId) {
      toast.error("Please select a branch first");
      return;
    }
    if (!values.items || values.items.length === 0) {
      toast.error("Please add at least one item");
      return;
    }

    setSubmitting(true);
    try {
      await createMutation.mutateAsync({
        branchId: activeBranchId,
        supplierId: values.supplierId,
        items: values.items.map((i: any) => ({
          ingredientId: i.ingredientId,
          quantity: i.quantity,
          price: i.price || 0
        }))
      });
      toast.success("Purchase Order created successfully");
      setIsModalOpen(false);
      form.resetFields();
    } catch (err: unknown) {
      if (err instanceof Error) toast.error(err.message || "Failed to create PO");
    } finally {
      setSubmitting(false);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "APPROVED": return "blue";
      case "RECEIVED": return "success";
      case "PENDING": return "warning";
      case "DRAFT": return "default";
      default: return "default";
    }
  };

  const getStepCurrent = (status: string) => {
    switch (status) {
      case "DRAFT": return 0;
      case "PENDING": return 1;
      case "APPROVED": return 2;
      case "RECEIVED": return 3;
      default: return 0;
    }
  };

  const canApprove = user?.role === "SUPER_ADMIN" || user?.role === "MANAGER";

  const columns = [
    {
      title: 'PO Number',
      key: 'poNumber',
      render: (_: any, record: any) => (
        <div className="flex items-center gap-2">
          <span className="font-semibold text-slate-800 dark:text-slate-200">{record.poNumber}</span>
          {record.isAutoGenerated && <Tag color="blue" className="text-[10px]">AUTO</Tag>}
        </div>
      ),
    },
    {
      title: 'Branch',
      dataIndex: ['branch', 'name'],
      key: 'branch',
    },
    {
      title: 'Supplier',
      dataIndex: ['supplier', 'name'],
      key: 'supplier',
    },
    {
      title: 'Created At',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => format(new Date(date), 'dd MMM yyyy HH:mm'),
    },
    {
      title: 'Status',
      key: 'status',
      render: (_: any, record: any) => (
        <Tag color={getStatusColor(record.status)} className="px-2 py-0.5 rounded-md font-medium tracking-wide">
          {record.status}
        </Tag>
      ),
    },
    {
      title: 'Action',
      key: 'action',
      align: 'right' as const,
      render: (_: any, po: any) => (
        <div className="flex justify-end gap-2">
          {po.status === 'PENDING' && canApprove && (
            <>
              <Popconfirm title="Approve this PO?" onConfirm={() => handleApprove(po.id)}>
                <AntButton type="primary" className="bg-blue-600 hover:bg-blue-700 border-none" size="small" icon={<CheckSquare className="w-3 h-3" />}>Approve</AntButton>
              </Popconfirm>
              <Popconfirm title="Reject this PO?" onConfirm={() => handleReject(po.id)}>
                <AntButton danger size="small" icon={<XCircle className="w-3 h-3" />}>Reject</AntButton>
              </Popconfirm>
            </>
          )}
          
          {po.status === 'APPROVED' && (
            <Popconfirm title="Confirm receive goods?" onConfirm={() => handleReceive(po.id)}>
              <AntButton type="primary" className="bg-emerald-500 hover:bg-emerald-600 border-none" size="small" icon={<CheckCircle2 className="w-3 h-3" />}>Receive</AntButton>
            </Popconfirm>
          )}
        </div>
      ),
    },
  ];

  const expandedRowRender = (record: any) => {
    const itemColumns = [
      { title: 'Ingredient', dataIndex: ['ingredient', 'name'], key: 'name' },
      { title: 'Quantity Req.', dataIndex: 'quantityRequested', key: 'qty', render: (val: number, rec: any) => `${val} ${rec.ingredient.unit}` },
      { title: 'Unit Price', dataIndex: 'unitPrice', key: 'price', render: (val: number) => `฿${Number(val).toFixed(2)}` },
      { title: 'Total', key: 'total', render: (_: any, rec: any) => `฿${(rec.quantityRequested * rec.unitPrice).toFixed(2)}` },
    ];

    const stepItems = [
      { title: "Draft", description: "Prepared" },
      { title: "Pending", description: "Approval" },
      { title: "Approved", description: "Waiting Delivery" },
      { title: "Received", description: "In Stock" }
    ];

    return (
      <div className="p-4 bg-slate-50/50 dark:bg-slate-900/50 rounded-lg m-2 border border-slate-100 dark:border-slate-800">
        <div className="mb-6 px-10">
          <Steps 
            current={getStepCurrent(record.status)} 
            size="small"
            status={record.status === 'DRAFT' && record.items.length > 0 && !record.isAutoGenerated ? 'error' : 'process'}
            items={stepItems}
          />
        </div>
        <Table 
          columns={itemColumns} 
          dataSource={record.items} 
          rowKey="id" 
          pagination={false} 
          size="small" 
          className="shadow-sm border border-slate-200 dark:border-slate-800 rounded-md overflow-hidden"
        />
      </div>
    );
  };

  return (
    <AnimatedPage className="space-y-6 w-full">
      <PageHeader 
        title="Purchase Orders"
        icon={Truck}
        description="Manage procurement orders and track deliveries."
        actions={
          <AntButton 
            type="primary" 
            className="bg-blue-600 hover:bg-blue-700 h-10 px-4 rounded-lg shadow-sm"
            icon={<Plus className="w-4 h-4" />}
            onClick={() => setIsModalOpen(true)}
            disabled={!activeBranchId}
          >
            Create PO
          </AntButton>
        }
      />

      <DataTable 
        columns={columns} 
        dataSource={pos} 
        rowKey="id"
        loading={loading}
        expandable={{ expandedRowRender }}
        pagination={{ pageSize: 10 }}
      />

      {/* Create PO Modal */}
      <FormModal
        title="Create Purchase Order"
        icon={Truck}
        isOpen={isModalOpen}
        onClose={() => { setIsModalOpen(false); form.resetFields(); }}
        width={800}
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleCreateSubmit}
          className="mt-6"
        >
          <Form.Item 
            label="Select Supplier" 
            name="supplierId" 
            rules={[{ required: true, message: 'Supplier is required' }]}
          >
            <Select 
              showSearch
              placeholder="Search and select supplier"
              optionFilterProp="children"
              className="h-10"
              options={suppliers.map((s: any) => ({ value: s.id, label: s.name }))}
            />
          </Form.Item>

          <div className="bg-slate-50 dark:bg-slate-950/50 p-4 rounded-xl border border-slate-200 dark:border-slate-800 mb-6">
            <h3 className="text-sm font-semibold mb-4 text-slate-700 dark:text-slate-300">Order Items</h3>
            <Form.List name="items">
              {(fields, { add, remove }) => (
                <>
                  {fields.map(({ key, name, ...restField }) => (
                    <div key={key} className="flex gap-4 items-start mb-4">
                      <Form.Item
                        {...restField}
                        name={[name, 'ingredientId']}
                        rules={[{ required: true, message: 'Missing ingredient' }]}
                        className="mb-0 flex-1"
                      >
                        <Select 
                          showSearch
                          placeholder="Ingredient"
                          options={ingredients.map((i: any) => ({ value: i.id, label: `${i.name} (${i.unit})` }))}
                          onChange={(val) => {
                            // Auto-fill price if available
                            const ing = ingredients.find((i: any) => i.id === val);
                            if (ing && ing.costPerUnit) {
                              const currentItems = form.getFieldValue('items');
                              currentItems[name].price = ing.costPerUnit;
                              form.setFieldsValue({ items: currentItems });
                            }
                          }}
                        />
                      </Form.Item>

                      <Form.Item
                        {...restField}
                        name={[name, 'quantity']}
                        rules={[{ required: true, message: 'Missing Qty' }]}
                        className="mb-0 w-32"
                      >
                        <InputNumber placeholder="Qty" min={0.1} step={0.1} className="w-full" />
                      </Form.Item>

                      <Form.Item
                        {...restField}
                        name={[name, 'price']}
                        rules={[{ required: true, message: 'Missing Price' }]}
                        className="mb-0 w-32"
                      >
                        <InputNumber placeholder="Price/Unit" min={0} className="w-full" />
                      </Form.Item>

                      <AntButton type="text" danger onClick={() => remove(name)} icon={<Trash2 className="w-4 h-4"/>} />
                    </div>
                  ))}
                  <Form.Item className="mb-0 mt-4">
                    <AntButton type="dashed" onClick={() => add()} block icon={<Plus className="w-4 h-4" />}>
                      Add Item
                    </AntButton>
                  </Form.Item>
                </>
              )}
            </Form.List>
          </div>

          <div className="flex justify-end gap-2">
            <AntButton onClick={() => setIsModalOpen(false)}>Cancel</AntButton>
            <AntButton type="primary" htmlType="submit" className="bg-blue-600" loading={submitting}>
              Submit PO
            </AntButton>
          </div>
        </Form>
      </FormModal>
    </AnimatedPage>
  );
}
